apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - update-container.yml
  - update-secrets.yml

configMapGenerator:
  - name: athari-iot-config-overrides
    files:
      - liquibase.properties