spring:
  cloud:
    config:
      enabled: false
      uri: http://localhost:11144
  application:
    name: iot-service
  datasource:
    driver-class-name: org.postgresql.Driver
    generate-unique-name: false
    name: athari_flowbox_iot
    username: flowbox@athari-flowbox-postgres
    password: kya3yqv*yqw*ENP*crg
    url: jdbc:postgresql://athari-flowbox-postgres.postgres.database.azure.com:5432/athari_flowbox_iot
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 3456
