spring:
  datasource:
    name: ${DATABASE_NAME}
    generate-unique-name: false
    url: jdbc:${DATABASE_TYPE}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
server:
  port: 22300
springdoc:
  swagger-ui:
    path: /