spring:
  application:
    name: iot-service
  datasource:
    name: ${DATABASE_NAME}
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  sql:
    init:
      mode: never
  liquibase:
    database-change-log-table: changelog
    enabled: true
    change-log: db/changelog/changelog-master.xml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
springdoc:
  swagger-ui:
    path: /