apiVersion: apps/v1
kind: Deployment
metadata:
  name: athari-iot-service
  namespace: athari
  labels:
    app: athari-iot-service
spec:
  replicas: 1
  template:
    metadata:
      name: athari-iot-service
      labels:
        app: athari-iot-service
    spec:
      containers:
        - name: athari-iot-service
          image: samtoya/athari-iot-service:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: athari-iot-config
                  key: database-name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: athari-iot-service-secrets
                  key: database-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: athari-iot-service-secrets
                  key: database-password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: athari-iot-service-secrets
                  key: database-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: athari-iot-config
                  key: database-port
      restartPolicy: Always

  selector:
    matchLabels:
      app: athari-iot-service
