apiVersion: v1
kind: Secret
metadata:
  name: athari-iot-service-secrets
  namespace: athari
type: Opaque
data:
  database-host: bG9jYWxob3N0Cg==
  database-username: c2FtdG95YQo=
  database-password: cGFzc3dvcmQK